### ISSUE TITLE
feat: DLT config and secrets integration

### ISSUE THREAD

**Issue by pgierz** [pgierz/slurm-monitor#25]
At the moment, I have (uncommitted) files related to `dlt` in my repo, under `.dlt/config.toml` and `.dlt/secrets.coml`.

Here are sample contents of these files, to be used for discussion, feature description, design, and implementation.

> `.dlt/config.toml`:
```toml
[runtime]
log_level="WARNING"  # the system log level of dlt

# REST API configuration
[sources.slurm]
base_url = "http://slurm:6820/slurm/v0.0.38"  # Replace with your SLURM REST API URL
generate_token = true     # Whether to generate a token on the fly using SSH
token_lifespan = 3600     # Token lifespan in seconds (1 hour)
days_back = 7  # Number of days to look back for job history

# SSH tunnel configuration (non-sensitive parts)
host = "albedo0.dmawi.de" # SSH jump host (e.g., "login.cluster.example.com")
port = 22                 # SSH port (usually 22)
remote_host = "slurm"     # SLURM server hostname/IP as seen from the SSH host
remote_port = 6820        # SLURM REST API port
local_port = 6820         # Local port to forward to

# SLURM API resources configuration
nodes = true            # Information about compute nodes
partitions = true       # Information about SLURM partitions/queues
jobs = true             # Information about jobs
job_details = true      # Detailed information about each job
cluster = true          # Cluster information
reservations = true     # Information about reservations
diag = true             # Diagnostic information
```

> `.dlt/secrets.toml`:
```toml
# SLURM API credentials
[sources.slurm.credentials]
username = "pgierz" # Your SLURM API username
password = ""       # Your SSH password (leave empty if using SSH key)
key_path = ""       # Path to your SSH private key (e.g., "/Users/username/.ssh/id_rsa")
token = ""          # Your SLURM API token, leave empty to generate one
```
